### ISSUE TITLE
Overwriting defaults are not working

### ISSUE THREAD

**Issue by Maybach91** [REHvision/kirby-seo-preview-section#2]
According to the readme, it should be possible to overwrite the fields on the page’ blueprint like so:

```yaml
  meta:
    extends: tabs/meta
    defaultDescription: page.description
```

Unfortunately overwriting is not working in general. `defaultTitle` is also not possible to overwrite.
If i set the `defaultDescription` within my `site/blueprints/tabs/meta.yml` to `page.description` it works. But thats just a workaround.
